<?php  $this->headTitle()->append(translate('ERROR')); ?>
<?php if (!isset($this->exception)) : ?>
<h1><?php echo translate($this->message);
?></h1>
<?php

echo translate($this->message.'_TEXT');

endif;
if (isset($this->exception)) :
?>
<b>Message:</b>
<pre><?php echo $this->exception->getMessage() ?></pre>
<br>

<b>Stack trace:</b>
<pre><?php echo $this->exception->getTraceAsString() ?></pre>
<br>

<b>Request Parameters:</b>
<pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
<?php endif ?>